targets = [
    "Cytochrome P450 19A1",
    "Muscarinic acetylcholine receptor M2",
    "Muscarinic acetylcholine receptors; M2 & M3",
    "Dopamine D3 receptor",
    "Dopamine D4 receptor",
    "Neprilysin",
    "Plasminogen",
    "Muscarinic acetylcholine receptor M1",
    "Angiotensin II receptor",
    "Serotonin 1a (5-HT1a) receptor",
    "Matrix metalloproteinase 3",
    "Matrix metalloproteinase-1",
    "Matrix metalloproteinase 9",
    "Matrix metalloproteinase-2",
    "ADAM17",
    "Peroxisome proliferator-activated receptor gamma",
    "Receptor protein-tyrosine kinase erbB-2",
    "Tyrosine-protein kinase LCK",
    "Angiotensin II type 2 (AT-2) receptor",
    "Serum albumin",
    "Adenosine A2a receptor",
    "Intercellular adhesion molecule-1",
    "Androgen Receptor",
    "Estrogen receptor",
    "Purinergic receptor P2Y2",
    "Excitatory amino acid transporter 1",
    "Excitatory amino acid transporter 2",
    "Excitatory amino acid transporter 3",
    "Caspase-1",
    "Caspase-3",
    "Caspase-6",
    "Caspase-8",
    "Renin",
    "Sigma opioid receptor",
    "Nitric oxide synthase, inducible",
    "Nitric-oxide synthase, endothelial",
    "Nitric-oxide synthase, brain",
    "Nitric oxide synthase (inducible and endothelial)",
    "Nitric oxide sythases; iNOS & nNOS",
    "P-selectin",
    "Complement C1r",
    "Type-1 angiotensin II receptor",
    "Serotonin 2c (5-HT2c) receptor",
    "Serotonin 2a (5-HT2a) receptor",
    "Monoamine oxidase A",
    "Butyrylcholinesterase",
    "Acetylcholinesterase",
    "Lipoprotein lipase",
    "Dopamine D1 receptor",
    "Cathepsin D",
    "Cathepsin G",
    "Cyclooxygenase-2",
    "Cyclooxygenase-1",
    "Cyclooxygenase",
    "Alpha-2a adrenergic receptor",
    "Dopamine transporter",
    "Serotonin 6 (5-HT6) receptor",
    "Calpain 1",
    "Glutamate receptor ionotropic, AMPA 1",
    "Glutamate receptor ionotropic, AMPA 2",
    "Glutamate receptor ionotropic, AMPA 3",
    "Cannabinoid CB2 receptor",
    "Cathepsin B",
    "Beta-secretase 1",
    "Adrenergic receptor beta",
    "Dopamine receptors; D3 & D4",
    "11-beta-hydroxysteroid dehydrogenase 1",
    "Monoamine oxidase B",
    "Tissue-type plasminogen activator",
    "Cytochrome P450 2D6",
    "HMG-CoA reductase",
    "TNF-beta",
    "Beta-2 adrenergic receptor",
    "Phospholipase A2 group IIA",
    "Serine/threonine-protein kinase RAF",
    "Gamma-secretase",
    "Estrogen receptor alpha",
    "Estrogen receptor beta",
    "Melatonin receptor 1A",
    "Melatonin receptor",
    "Arachidonate 5-lipoxygenase",
    "Muscarinic acetylcholine receptor M2 and M4",
    "Muscarinic acetylcholine receptor M2 and M5",
    "Beta-glucocerebrosidase",
    "Serum paraoxonase/arylesterase 1",
    "Angiotensin-converting enzyme",
    "Dopamine receptor",
    "GABA-B receptor",
    "Muscarinic acetylcholine receptor",
    "Cytochrome P450 17A1",
    "FK506 binding protein 12",
    "Cyclin-dependent kinase 1",
    "Amyloid-beta A4 protein",
    "Farnesyl diphosphate synthase",
    "Corticotropin releasing factor receptor 1",
    "Cyclin-dependent kinase 5/CDK5 activator 1",
    "Glycogen synthase kinase-3",
    "Neuronal acetylcholine receptor; alpha4/beta2",
    "Neuronal acetylcholine receptor protein alpha-7 subunit",
    "Gamma-secretase subunit PEN-2",
    "Erythropoietin receptor",
    "Purine nucleoside phosphorylase",
    "C-C chemokine receptor type 5",
    "C-C chemokine receptor type 3",
    "Urokinase-type plasminogen activator",
    "C5a anaphylatoxin chemotactic receptor",
    "Macrophage migration inhibitory factor",
    "Dual specificity mitogen-activated protein kinase kinase 1",
    "Tyrosine-protein kinase FYN",
    "Serotonin transporter",
    "Acyl coenzyme A:cholesterol acyltransferase 1",
    "Peroxisome proliferator-activated receptor alpha",
    "Peroxisome proliferator-activated receptor delta",
    "P-glycoprotein 1",
    "Tyrosine-protein kinase ABL",
    "Neuronal acetylcholine receptor; alpha3/beta4",
    "Glycogen synthase kinase-3 beta",
    "Angiotensin-converting enzyme",
    "Voltage-gated L-type calcium channel alpha-1C subunit",
    "Glycogen synthase kinase-3 alpha",
    "Monoamine oxidase",
    "Beta-secretase (BACE)",
    "Plasminogen activator inhibitor-1",
    "Matrix metalloproteinase (2 and 3)",
    "Transthyretin",
    "Monoamine transporters; serotonin & dopamine",
    "Matrix metalloproteinase 12",
    "Mitogen-activated protein kinase; ERK1/ERK2",
    "Ribosomal protein S6 kinase (P70S6K)",
    "Serine/threonine-protein kinase AKT",
    "Dual-specificity tyrosine-phosphorylation regulated kinase 1A",
    "MAP kinase ERK1",
    "MAP kinase ERK2",
    "Tyrosine-protein kinase ABL",
    "PPAR alpha/gamma",
    "Insulin-like growth factor binding protein 3",
    "TNF-alpha",
    "Receptor-type tyrosine-protein phosphatase alpha",
    "Glutamate receptor ionotropic AMPA",
    "Prolyl endopeptidase",
    "Insulin-like growth factor binding protein 2",
    "Insulin-like growth factor binding protein 6",
    "Ceramide glucosyltransferase",
    "Insulin-like growth factor I receptor",
    "Insulin receptor",
    "Dual specificity mitogen-activated protein kinase kinase; MEK1/2",
    "Glyceraldehyde-3-phosphate dehydrogenase liver",
    "Adenosine receptors; A2a & A3",
    "Caspase-9",
    "Vitamin D receptor",
    "Vesicular acetylcholine transporter",
    "Nerve growth factor receptor Trk-A",
    "Dual specificity mitogen-activated protein kinase kinase 2",
    "Subtilisin/kexin type 9",
    "GAR transformylase",
    "Anandamide amidohydrolase",
    "Quinone reductase 1",
    "Muscarinic acetylcholine receptor M1 and M3",
    "Thioredoxin reductase",
    "Caspase-7",
    "Phenylethanolamine N-methyltransferase",
    "Serotransferrin",
    "CaM kinase II",
    "Vascular endothelial growth factor A",
    "Glutamine synthetase",
    "Arachidonate 15-lipoxygenase",
    "Complement factor H",
    "Tumor necrosis factor receptor R1",
    "G-protein coupled receptor kinase 2",
    "Arachidonate 12-lipoxygenase",
    "Phosphodiesterase 4B",
    "Beta-2 adrenergic receptor and beta-3 adrenergic receptor",
    "RXR alpha/PPAR gamma",
    "Serine/threonine-protein kinase RAF and Dual specificity mitogen-activated protein kinase kinase 1 (Raf/MEK)",
    "Glutathione S-transferase Pi",
    "Cyclin-dependent kinase 5",
    "Bcr/Abl fusion protein",
    "Caspase-2",
    "Caspase-4",
    "Interleukin-8 receptor B",
    "Neuronal acetylcholine receptor; alpha2/beta4",
    "Superoxide dismutase",
    "Lysosomal acid lipase/cholesteryl ester hydrolase",
    "Neuronal acetylcholine receptor subunit alpha-3",
    "Phosphatidylcholine-retinol O-acyltransferase",
    "Cannabinoid receptor",
    "Nitric-oxide synthase (endothelial and brain)",
    "Neuronal acetylcholine receptor; alpha3/beta2",
    "Beta secretase 2",
    "Glutamate (NMDA) receptor subunit zeta 1",
    "Cystic fibrosis transmembrane conductance regulator",
    "Inositol 1,4,5-trisphosphate receptor type 1",
    "Glutamate [NMDA] receptor subunit epsilon 1",
    "Glutamate [NMDA] receptor subunit epsilon 2",
    "Poly [ADP-ribose] polymerase-1",
    "DNA polymerase beta",
    "Choline acetylase",
    "Catechol O-methyltransferase",
    "Cathepsin (B and K)",
    "C-X-C chemokine receptor type 3",
    "Glutamate NMDA receptor; GRIN1/GRIN2A",
    "Glutamate NMDA receptor; GRIN1/GRIN2B",
    "Serine/threonine-protein kinase WEE1",
    "Aryl hydrocarbon receptor",
    "Collagenase",
    "Aldehyde dehydrogenase",
    "Receptor protein-tyrosine kinase erbB-4",
    "PI3-kinase p110-alpha/p85-alpha",
    "Cytochrome P450 1A1",
    "Proenkephalin B",
    "5-lipoxygenase/FLAP",
    "LDL receptor",
    "Interleukin-8",
    "Myeloperoxidase",
    "cAMP-dependent protein kinase alpha-catalytic subunit",
    "Prion protein",
    "Low affinity neurotrophin receptor p75NTR",
    "Cerebroside-sulfatase",
    "Quinone reductase 2",
    "Suv3 helicase",
    "Ribosomal protein S6 kinase 1",
    "Serum amyloid P-component",
    "HLA class I histocompatibility antigen A-3",
    "Acidic fibroblast growth factor",
    "HLA class II histocompatibility antigen, DRB1-15 beta chain",
    "Peptidyl-prolyl cis-trans isomerase NIMA-interacting 1",
    "Insulin-like growth factor II receptor",
    "PPAR delta/gamma",
    "Neuronal acetylcholine receptor; alpha2/beta2",
    "Tumour suppressor p53/oncoprotein Mdm2",
    "Prostaglandin E synthase 2",
    "Casein kinase I delta",
    "Fatty acid binding protein muscle",
    "ADAMTS4",
    "ADAM12",
    "ADAM10",
    "Breakpoint cluster region protein",
    "S-100 protein beta chain",
    "Serine/threonine-protein kinase EEF2K",
    "LXR-beta",
    "Coagulation factor XIII",
    "Kinesin-like protein 1",
    "Eukaryotic translation initation factor",
    "Guanine nucleotide-binding protein G(o), alpha subunit 1",
    "CaM kinase II alpha",
    "Ephrin type-A receptor 5",
    "CaM kinase II gamma",
    "CaM kinase I alpha",
    "Serine/threonine-protein kinase PAK 1",
    "NAD-dependent deacetylase sirtuin 1",
    "Toll-like receptor 4",
    "Phosphodiesterase 8B",
    "Synaptic vesicular amine transporter",
    "Apoptosis regulator Bcl-W",
    "Coagulation factor V",
    "ADAMTS1",
    "Neurotrophic tyrosine kinase receptor type 2",
    "Luteinizing hormone/Choriogonadotropin receptor",
    "Heme oxygenase 1",
    "Insulin",
    "Muscarinic acetylcholine receptor M1/M5 chimeric protein",
    "Catenin beta-1",
    "Phosphoenolpyruvate carboxykinase cytosolic",
    "Interferon-induced, double-stranded RNA-activated protein kinase",
    "Alpha-1-antichymotrypsin",
    "Ubiquitin carboxyl-terminal hydrolase isozyme L1",
    "Breast cancer type 1 susceptibility protein",
    "Alpha-synuclein",
    "Segment polarity protein dishevelled homolog DVL-1",
    "Nucleoside diphosphate kinase 1",
    "Nucleoside diphosphate kinase 2",
    "Cyclin-dependent kinase 5 regulatory subunit 1",
    "PI3-kinase p85-alpha subunit",
    "Ornithine aminotransferase, mitochondrial",
    "Ephrin type-A receptor 1",
    "Death-associated protein kinase 1",
    "Serine/threonine-protein kinase 11",
    "Serine/threonine-protein kinase MARK1",
    "Serine/threonine-protein kinase 24",
    "Protein tyrosine kinase 2 beta",
    "Apolipoprotein A-I",
    "Thioredoxin reductase 2",
    "NT-3 growth factor receptor",
    "Receptor tyrosine-protein kinase erbB-3",
    "Interleukin-2",
    "Presenilin 1",
    "Cellular tumor antigen p53",
    "DNA-(apurinic or apyrimidinic site) lyase",
    "Neuronal acetylcholine receptor protein alpha-4 subunit",
    "Glutathione transferase omega 1",
    "Huntingtin",
    "Macrophage scavenger receptor types I and II",
    "Cyclic AMP-responsive element-binding protein 1",
    "Disks large homolog 4",
    "Tumor necrosis factor ligand superfamily member 10",
    "Tumor necrosis factor ligand superfamily member 6",
    "Arylamine N-acetyltransferase 1",
    "Arylamine N-acetyltransferase 2",
    "Toll-like receptor 9",
    "GABA-B receptor 1",
    "Tryptophan 5-hydroxylase 1",
    "Glucagon",
    "Non-receptor tyrosine-protein kinase TNK1",
    "Histone acetyltransferase KAT5",
    "Endoplasmic reticulum aminopeptidase 1",
    "Adenylate cyclase type II",
    "Aquaporin-4",
    "Peroxiredoxin-1",
    "Acid ceramidase",
    "Heat shock 70 kDa protein 1",
    "Dynamin-2",
    "Transcription factor Sp1",
    "Creatine kinase B-type",
    "Dickkopf-related protein 1",
    "Kallikrein 8",
    "Leucine-rich repeat serine/threonine-protein kinase 2",
    "Integrin alpha M",
    "Elongation factor 2",
    "Tumor necrosis factor receptor superfamily member 5",
    "Tumor necrosis factor receptor superfamily member 1B",
    "Toll-like receptor (TLR7/TLR9)",
    "MIF/CD74 (Macrophage migration inhibitory factor and HLA-DR antigens-associated invariant chain)",
    "Eukaryotic translation initiation factor 2 subunit 1",
    "PI3-kinase p110-delta/p85-alpha",
    "C-C motif chemokine 5",
    "Transcriptional regulator ERG",
    "Prelamin-A/C",
    "Microtubule-associated protein tau",
    "Endoplasmic reticulum-associated amyloid beta-peptide-binding protein",
    "Peroxisome proliferator-activated receptor gamma/Nuclear receptor coactivator 1",
    "Peroxisome proliferator-activated receptor gamma/Nuclear receptor corepressor 2",
    "Ubiquitin carboxyl-terminal hydrolase BAP1",
    "Peroxisome proliferator-activated receptor gamma/Nuclear receptor coactivator 2",
    "Insulin-degrading enzyme",
    "Peroxisome proliferator-activated receptor gamma/Nuclear receptor coactivator 3",
    #"Excitatory amino acid transporter 5",
    "Relaxin-3 receptor 1",
    "Neuronal acetylcholine receptor subunit alpha-6/beta-2",
    "C-C motif chemokine 2",
    "Neuronal acetylcholine receptor protein beta-2 subunit",
    "Peptidyl-prolyl cis-trans isomerase D",
    "Glutathione S-transferase A4",
    "Glutathione transferase omega 2",
    "Platelet glycoprotein 4",
    "G1/S-specific cyclin D1",
    "78 kDa glucose-regulated protein",
    "Interleukin-6",
    #"Somatostatin",
    "Somatostatin receptor 1",
    "Somatostatin receptor 2",
    "Somatostatin receptor 3",
    "Somatostatin receptor 4",
    "Somatostatin receptor 5",
    "Bis(5'-adenosyl)-triphosphatase",
    "Protein polybromo-1",
    "Transforming growth factor beta-1",
    "Kallikrein 7",
    "Regulator of G-protein signaling 4",
    "Protein-arginine deiminase type-2",
    "Interleukin-1 beta",
    "Scavenger receptor class B member 1",
    "Islet amyloid polypeptide",
    "Appetite-regulating hormone",
    "Protoporphyrinogen oxidase",
    "Natural resistance-associated macrophage protein 2",
    "Proteasome subunit beta type-9",
    "DNA polymerase nu",
    "NEDD8-activating enzyme E1 regulatory subunit",
    "Neuronal acetylcholine receptors; alpha-3/beta-4, alpha-5, beta-2",
    "Kallikrein 6",
    "Phosphatidylinositol 3,4,5-trisphosphate 3-phosphatase and dual-specificity protein phosphatase PTEN",
    "Natural resistance-associated macrophage protein 1",
    "Heat shock-related 70 kDa protein 2",
    "ATP synthase subunit alpha, mitochondrial",
    "Guanine nucleotide-binding protein G(s), subunit alpha",
    "Neurogenic locus notch homolog protein 1",
    "Methionine synthase",
    "Ubiquitin carboxyl-terminal hydrolase 21",
    "Presenilin 2",
    "Advanced glycosylation end product-specific receptor",
    "Tumour suppressor protein p53/Mdm4",
    "mTORC1",
    "High mobility group protein B1",
    "Alpha-ketoglutarate-dependent dioxygenase FTO",
    "TAR DNA-binding protein 43",
    "Muscarinic acetylcholine receptors; M1 & M2",
    "Neuronal acetylcholine receptor; alpha4/beta4",
    "Adenosine receptors; A1 & A2",
    "Dopamine D2 receptor and serotonin 1a receptor",
    "Cholinesterases; ACHE & BCHE",
    "Serotonin 2 receptors; 5-HT2a & 5-HT2c",
    "Serotonin receptor (2b and 2c)",
    "Neuronal acetylcholine receptor; alpha3/alpha6/beta2/beta3"
]